# Generated by Django 4.2 on 2023-04-08 04:05
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone 



class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_article_topic_delete_blogapp_article_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
